name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name Debug
        run: echo ${{ GITHUB_ACTOR }}

      # - name: Checkout Repo
      #   uses: actions/checkout@master
      #   with:
      #     submodules: true
      # - name: Publish Site
      #   uses: chabad360/hugo-gh-pages@master
      #   with:
      #     githubToken: ${{ secrets.DEPLOY_TOKEN }}
