name: Publish Site

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.71.1'
          # extended: true

      - name: Build
        run: hugo

      - name: Deploy to GitHub Pages
        uses: cecilapp/github-pages-deploy@master
        env:
          EMAIL: superruzafa@gmail.com
          GH_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BUILD_DIR: public